version: '3'
services:
  ocr:
    image: "mysql:5.7.10"
    container_name: "epione"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "epione"
      MYSQL_DATABASE: "epione"
    volumes:
      - ocr_db:/var/lib/mysql
volumes:
  ocr_db:
    driver: "local"
